name: CI Pipeline

on:
  push:
    branches:
      - main  # main 브랜치로 push될 때 실행
  pull_request:
    branches:
      - main  # main 브랜치로 PR 생성 시 실행

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest  # 테스트 환경: 최신 Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Python 버전 지정

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest  # pytest로 테스트 실행

    - name: Lint code with pylint
      run: |
        pylint app.py
